config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to:'home#top'
  get 'home/about' => 'home#about'
  get '/search', to: 'searches#search'

  resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
  resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
belongs_to :user
has_many :favorites, dependent: :destroy
has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

validates :title, presence: true
validates :body, presence: true, length: {maximum:200}

def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :book_comments, dependent: :destroy

 attachment :profile_image

  validates :name, presence: true , uniqueness: true , length: { in:2..20 }
  validates :introduction, length: {maximum: 50}

has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
     user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    before_action :authenticate_user!


  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.user_id = current_user.id
    unless @book_comment.save
      redirect_to book_path(book.id)
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!
 before_action :ensure_correct_user, only: [:edit, :update, :destroy]


  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def new
    @book.save
    flash[:danger] = "You have created book successfully."
  end

  def show
    @book_new = Book.new
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @books = Book.all
    @book = Book.find(params[:id])
    @user = current_user
    if @book.user == current_user
       render "edit"
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
       flash[:danger] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:danger] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private



  def book_params
    params.require(:book).permit(:title, :body)
  end


  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def top
  @book = Book.new
 end

 def about
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top
  @book = Book.new
 end

 def about
 end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    	@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Book.search_for(@content, @method)
		end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @book_new = Book.new
    @users = User.all
    @user = current_user
  end


  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end


  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
       render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:danger] = "You have created book successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
  unless @user == current_user
      redirect_to user_path(current_user)
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
  <% book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
     <td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
      <% end %>
     </tr>
    <% end %>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/books/_list.html.erb
 <% if book.errors.any? %>
  <%= pluralize(book.errors.count, "error") %>
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

    <div class='container'>
      <div class='row'>
        <div class='col-md-3'>

    <h2>User info</h2>

 <table class="table">
 <tr><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></tr>
 <tr>
  <th>name:<%= user.name %></th>
 </tr>
 <tr>
  <th>introduction:<%= user.introduction %></th>
 </tr>
 <tr>
     <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% end %>
  </div>
</table>


    <h2 class="mt-3">New book</h2>

      <%= form_with model:book, url:'/books', local:true do |f| %>

  <div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title %>
  </div>

  <div class="form-group">
  <label for="book_opinion">Opinion</label></br>
  <%= f.text_field :body %>
  </div>

  <div class="form-group">
  <%= f.submit 'Create Book' %>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<main>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
 <div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

 <% if @book.errors.any? %>
  <%= pluralize(@book.errors.count, "error") %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


  <div class="form-group">
    <label for="book_title">Title</label></br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label></br>
    <%= f.text_area :body %></br>
  </div>
  <div class="form-group">
    <%= f.submit 'Update Book'%></br>
  </div>
  <span><%= link_to 'Show' , book_path %></span>|
  <span><%= link_to 'Back' , books_path %></span>
  <% end %>

  </div>
</div>
</main>

app/views/books/index.html.erb
<main>

    <% if user_signed_in? %>
    <%= render 'layouts/search' %>
    <% end %>
<%= render'books/list',user: @user,book: @book%>

<div class='col-md-8 offset-md-1'>
     <h2>Books</h2>
 <table class='table table-hover table-inverse'>

      <thead>
         <th> Title</th>
         <th> Opinion</th>
        <th colspan="3"></th>
     </thead>

     <% @books.each do |book| %>
     <tr id="book_<%= book.id %>">

    <td><%= link_to (attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40"), user_path(book.user.id) %></td>

     <td><%= link_to book.title, book_path(book.id)%></td>
      <td><%= book.body %></td>

  <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
      <td>コメント数: <%= book.book_comments.count %></td>

   </tr>

      <% end %>


  </table>

</div>

</main>

app/views/books/show.html.erb
<main>
<%= flash[:danger] %>
 <%= render'books/list',user: @user,book: @book_new%>
 <div class='col-md-8 offset-md-1'>
   <h2>Book detail</h2>
   <table class='table'>


 <thead>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
 </thead>


   <tr id="book_<%= @book.id %>">

    <td><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",size:"40x40" %></br>
    <%= link_to @user.name, user_path(@book.user) %></td>
    <td><%= @book.title %></td>
    <td><%= @book.body %></td>

    <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>

    <% if @user.id == current_user.id %>
    <td><%= link_to 'Edit', edit_book_path, class: "btn btn-secondary" %></td>
    <td><%= link_to 'Destroy', book_path,method: :delete ,class: "btn btn-secondary" %></td>
    <% end %>
    <th colspan="3"></th>
</table>

  <table class="book_comments">
      <%= render 'book_comments/index', book: @book %>
    </table>
 <td>

<%= form_with model:[@book, @book_comment] do |f| %>
  <%= f.text_area :comment, rows:'5' %>
  <%= f.submit "送信" %>
<% end %>
</td>
   </tr>


 </table>

 </div>

</main>

app/views/favorites/_favorite-btn.html.erb
  <% if book.favorited_by?(current_user) %>

      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        ♥<%= book.favorites.count %>
      <% end %>

    <% else %>

      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        ♡<%= book.favorites.count %>
      <% end %>

      <% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/home/about.html.erb
   <main>
    <p id="notice"></p>
    <div class='container'>
    <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
  </div>
  </main>
   <footer>
    <div class='container mt-5'>
    <div class='row'>
    <div class='mx-auto'>
  </div>
  </div>
  </div>

app/views/home/new.html.erb
  <main>
 <%= render'books/list',user:@user,book:@book%>
  <div class='col-md-9'>
     <h2>Books</h2>
 <table class='table table-hover table-inverse'>

      <thead>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
     </thead>
     <% @books.each do |book| %>
     <tr>
    <%= attachment_image_tag @post_image, :image %>
     <td><%= book.title %></td>
      <td><%= book.body %></td>
     </tr>
      <% end %>

  </table>

</div>

</main>

app/views/home/top.html.erb
<html>
  <head>
    <title>Bookers2 top</title>

  <body>

      <main>

  <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
         <div class="row">
        <%= link_to "Log in" , new_user_session_path, class: "login btn btn-info btn-sm btn-block mb-3 sign_in " %>
        </div>
        <div class="row">
        <%= link_to "Sign up" , new_user_registration_path, class:"signup btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

      </main>
  </body>
</html>

app/views/homes/top.html.erb
<html>
  <head>
    <title>Bookers2 top</title>

  <body>

      <main>
        <p id="notice">Signed out successfully.</p>
        <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
         <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

      </main>
  </body>
</html>

app/views/users/_list.html.erb
 <div class='container'>
  <div class='row'>
  <div class='col-md-3'>
    <h2>User info</h2>

 <table class="table">
 <tr><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></tr>
 <tr>
  <th>name:<%= user.name %></th>
 </tr>
 <tr>
  <th>introduction:<%= user.introduction %></th>
 </tr>
 <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% end %>
  </div>



    <h2 class="mt-3">New book</h2>
      <%= form_with model:book, url:'/books', local:true do |f| %>

  <div class="form-group">
  <label for="book_title">Title</label></br>
  <%= f.text_field :title %>
  </div>

  <div class="form-group">
  <label for="book_opinion">Opinion</label></br>
  <%= f.text_field :body %>
  </div>

  <div class="form-group">
  <%= f.submit 'Create Book' %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<main>
<div class='container'>
<div class='row'>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>

 <% if @user.errors.any? %>
  <%= pluralize(@user.errors.count, "error") %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class="form-group">
  <label for="user_name">Name</label></br>
  <%= f.text_field :name, autofocus: true, id:"user_", placeholder:"Name"%>
  </div>

 <div class="form-group">
  <label for="inputImage">Image</label></br>
  <%= f.attachment_field :profile_image, placeholder: "Image" %>
 </div>

<div class="form-group">
  <label for="inputIntroduction">Introduction</label></br>
  <%= f.text_field :introduction %></br>
  <%= f.submit "Update User", class:"btn btn-secondary" %>
</div>

<% end %>
</div>
</div>
</div>
</main>

app/views/users/index.html.erb
 <main>
     <% if user_signed_in? %>
    <%= render 'layouts/search' %>
    <% end %>
<%= render'users/list',user: @user,book: @book_new%>

   <div class='col-md-8 offset-md-1'>
     <h2>Users</h2>
 <table class='table table-hover table-inverse'>
 <thead>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
  </thead>

  <% @users.each do |user| %>
  <tr>
  <td><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",size:"40x40" %></td>
  <td><%=user.name %></td>
  <td>フォロー数: <%= user.followings.count %></td>
  <td>フォロワー数: <%= user.followers.count %></td>
  <td>
    <% if current_user != user %>
       <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
       <% else %>
         <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
      <% end %>
      <% end %>
  </td>
  <td><%= link_to 'Show', user_path(user) %></td>
  </tr>
  <% end %>

</table>

</div>

</main>

app/views/users/show.html.erb
 <main>
  <%= flash[:danger] %>
<%= render'users/list', user:@user,book:@book%>
   <div class='col-md-8 offset-md-1'>
     <h2>Books</h2>
 <table class='table table-hover table-inverse'>

 <thead>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </thead>

 <% @books.each do |book| %>
  <tr>
  <td><%= link_to (attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg",size:"40x40"), user_path(@user.id) %></td>
     <td><%= link_to book.title, book_path(book.id)%></td>
      <td><%= book.body %></td>
  </tr>
 <% end %>
  </table>
</div>
</main>